import reflex as rx

def hero() -> rx.Component:
    return rx.box(
        rx.vstack(
            rx.heading(
                "John Doe",
                size="1",
                background="linear-gradient(135deg, #006FEE 0%, #00E075 100%)",
                background_clip="text",
                webkit_background_clip="text",
                color="transparent",
                font_weight="900",
                font_size="8xl",
                text_align="center",
                letter_spacing="-0.02em",
                margin_bottom="6",
                text_shadow="0 4px 12px rgba(0, 0, 0, 0.1)",
            ),
            rx.text(
                "Full Stack Developer & Software Engineer",
                color="gray.700",
                font_size="3xl",
                text_align="center",
                font_weight="semibold",
                _dark={"color": "gray.200"},
                letter_spacing="-0.01em",
            ),
            rx.text(
                "Building innovative solutions with modern technologies.",
                color="gray.600",
                font_size="xl",
                text_align="center",
                margin_top="8",
                _dark={"color": "gray.400"},
                max_width="600px",
            ),
            rx.hstack(
                rx.link(
                    rx.button(
                        "View Projects",
                        size="4",
                        bg="blue.500",
                        color="white",
                        padding_x="8",
                        padding_y="6",
                        _hover={
                            "bg": "blue.600",
                            "transform": "translateY(-2px)",
                            "shadow": "xl",
                        },
                        _active={"transform": "translateY(0)"},
                        _dark={
                            "bg": "blue.400",
                            "_hover": {"bg": "blue.500"},
                        },
                        transition="all 0.2s cubic-bezier(.17,.67,.83,.67)",
                    ),
                    href="#projects",
                ),
                rx.link(
                    rx.button(
                        "Contact Me",
                        size="4",
                        variant="outline",
                        border_color="blue.500",
                        color="blue.500",
                        border_width="2px",
                        padding_x="8",
                        padding_y="6",
                        _hover={
                            "bg": "blue.50",
                            "transform": "translateY(-2px)",
                            "shadow": "xl",
                        },
                        _active={"transform": "translateY(0)"},
                        _dark={
                            "color": "blue.200",
                            "border_color": "blue.200",
                            "_hover": {"bg": "rgba(0, 111, 238, 0.1)"},
                        },
                        transition="all 0.2s cubic-bezier(.17,.67,.83,.67)",
                    ),
                    href="#contact",
                ),
                spacing="6",
                margin_top="16",
            ),
            spacing="6",
            padding_y="32",
            max_width="1200px",
            margin="0 auto",
            width="100%",
        ),
        width="100%",
        min_height="100vh",
        background="radial-gradient(circle at 50% 50%, rgba(0, 111, 238, 0.1) 0%, rgba(255, 255, 255, 0) 50%)",
        _dark={"background": "radial-gradient(circle at 50% 50%, rgba(0, 111, 238, 0.05) 0%, rgba(0, 0, 0, 0) 50%)"},
        display="flex",
        align_items="center",
        justify_content="center",
    )
