"""empty message

Revision ID: a44b668a0598
Revises: be11b7968912
Create Date: 2023-11-09 07:33:35.646037

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision = 'a44b668a0598'
down_revision = 'be11b7968912'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('response', sa.Column('client_token', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('response', 'client_token')
    # ### end Alembic commands ###
