"""empty message

Revision ID: a7788bf82fa0
Revises: cc9cc858ab54
Create Date: 2024-04-10 16:04:42.644301

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision = 'a7788bf82fa0'
down_revision = 'cc9cc858ab54'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('option', 'foobar')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('option', sa.Column('foobar', sa.INTEGER(), server_default=sa.text('(423)'), nullable=False))
    # ### end Alembic commands ###
