"""empty message

Revision ID: cc9cc858ab54
Revises: a44b668a0598
Create Date: 2023-12-12 13:57:08.500771

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision = 'cc9cc858ab54'
down_revision = 'a44b668a0598'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('option', sa.Column('foobar', sa.Integer(), server_default=sa.text('(423)'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('option', 'foobar')
    # ### end Alembic commands ###
