"""empty message

Revision ID: b4f29dafaf7c
Revises: cd0c41e31106
Create Date: 2025-10-02 15:15:26.603719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'b4f29dafaf7c'
down_revision: Union[str, Sequence[str], None] = 'cd0c41e31106'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('like',
    sa.Column('tweet_id', sa.Integer(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('tweet_id', 'username')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_photo', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("('')"), nullable=False))
        batch_op.add_column(sa.Column('bio', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("('')"), nullable=False))
        batch_op.add_column(sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("('')"), nullable=False))
        batch_op.add_column(sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("('')"), nullable=False))
        batch_op.add_column(sa.Column('website', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("('')"), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('website')
        batch_op.drop_column('location')
        batch_op.drop_column('display_name')
        batch_op.drop_column('bio')
        batch_op.drop_column('profile_photo')

    op.drop_table('like')
    # ### end Alembic commands ###
