"""something changed.

Revision ID: e565fdc23e6c
Revises: 333b61328fdd
Create Date: 2024-01-23 13:49:28.720768

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e565fdc23e6c"
down_revision: Union[str, None] = "333b61328fdd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("customer", "edit")
    op.drop_column("customer", "icon")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "customer", sa.Column("icon", sa.VARCHAR(), autoincrement=False, nullable=False)
    )
    op.add_column(
        "customer", sa.Column("edit", sa.VARCHAR(), autoincrement=False, nullable=False)
    )
    # ### end Alembic commands ###
